// Code generated by MockGen. DO NOT EDIT.
// Source: repositories/flight_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "airline-booking/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFlightRepository is a mock of FlightRepository interface.
type MockFlightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFlightRepositoryMockRecorder
}

// MockFlightRepositoryMockRecorder is the mock recorder for MockFlightRepository.
type MockFlightRepositoryMockRecorder struct {
	mock *MockFlightRepository
}

// NewMockFlightRepository creates a new mock instance.
func NewMockFlightRepository(ctrl *gomock.Controller) *MockFlightRepository {
	mock := &MockFlightRepository{ctrl: ctrl}
	mock.recorder = &MockFlightRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightRepository) EXPECT() *MockFlightRepositoryMockRecorder {
	return m.recorder
}

// SearchFlights mocks base method.
func (m *MockFlightRepository) SearchFlights(ctx context.Context, req models.SearchRequest) ([]models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFlights", ctx, req)
	ret0, _ := ret[0].([]models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFlights indicates an expected call of SearchFlights.
func (mr *MockFlightRepositoryMockRecorder) SearchFlights(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFlights", reflect.TypeOf((*MockFlightRepository)(nil).SearchFlights), ctx, req)
}
